import type { Metadata } from "next"
import { Roboto_Slab, Bebas_Neue } from "next/font/google"
import "./globals.css"
import { ThemeProvider } from "./context/ThemeContext"

const robotoSlab = Roboto_Slab({
  subsets: ["latin"],
  variable: "--font-robotoSlab",
  weight: ["400"],
})

const bebas = Bebas_Neue({
  subsets: ["latin"],
  variable: "--font-bebas",
  weight: ["400"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={`${robotoSlab.variable} ${bebas.variable}`}
      >
        <ThemeProvider>
        {children}
        </ThemeProvider>
      </body>
    </html>
  )
}